### ISSUE TITLE
The created python bot isn't set up properly for testing

### ISSUE THREAD

**Issue by cniekel** [RLBot/RLBotGUI#46]
When clicking the 'start a new bot', it downloads some files, and does some filename-mangling, but one is missed.

When generating bot 'test', the file test/training/hello_world_training.py  in make_match_config_with_my_bot should not use 'python_example' / 'python_example.cfg' as path, but 'generated_name' / 'generated_name.cfg'

**Comment by tarehart** [comment]
In retrospect, the filename-mangling was a bad idea. 

It was very common for beginners to rename all those files manually, maybe in part because of https://youtu.be/NjJzPoo16iQ?t=141. Most made mistakes and needed help so I was trying to automate that, *but* clearly the mangling is not very maintainable. 

My current idea is to change the RLBotPythonExample repo to have very generic-sounding file names like 'bot.py', 'bot.cfg' so that people feel less compelled to change them, and stop modifying them in the new bot script. I would only set the in-game name in the cfg file.

**Comment by cniekel** [comment]
If the example would have standard names, that might be better. Calling it a src-dir rather than Example would also remove the stutter of "Mybots/botname/botbame/botname.py"

Mybots/botbame/src/bot.py would be handier, would make the file from training unchanging
